"""Change type of Activity.distance to Float

Revision ID: 747acd9713c9
Revises: d47dde3b72c8
Create Date: 2022-03-09 20:46:20.902590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747acd9713c9'
down_revision = 'd47dde3b72c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
