"""Change Primary_Photo primarykey

Revision ID: b635c5d64e11
Revises: 6a4ef00bcea0
Create Date: 2022-03-09 09:23:47.343921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b635c5d64e11'
down_revision = '6a4ef00bcea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_photo', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primary_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
